server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
      password: root
      url: jdbc:postgresql://localhost:5432/customer
      username: root
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        hibernate:
          dll-auto: update
        show-sql: true
